"""Adding reassigned field to hotel_request

Revision ID: 03fa60ed8de2
Revises: d176e999529c
Create Date: 2021-11-20 01:28:36.234810

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03fa60ed8de2'
down_revision = 'd176e999529c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hotel_room_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assigned', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hotel_room_request', schema=None) as batch_op:
        batch_op.drop_column('assigned')

    # ### end Alembic commands ###
