"""Added timezone to event

Revision ID: 28e0b36a0af8
Revises: afc23d43704e
Create Date: 2025-06-25 21:54:34.030171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28e0b36a0af8'
down_revision = 'afc23d43704e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timezone', sa.String(), nullable=False, server_default="America/New_York"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_column('timezone')

    # ### end Alembic commands ###
