"""Improving uber auth flow

Revision ID: 3dd38bec527c
Revises: a19f71e34e64
Create Date: 2021-10-25 20:25:43.348881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3dd38bec527c'
down_revision = 'a19f71e34e64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('badge', schema=None) as batch_op:
        batch_op.add_column(sa.Column('public_name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('emergency_contact_name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('emergency_contact_phone', sa.String(), nullable=True))

    with op.batch_alter_table('hotel_location', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'event', ['event'], ['id'])

    with op.batch_alter_table('session', schema=None) as batch_op:
        batch_op.add_column(sa.Column('badge', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'badge', ['badge'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('badge')

    with op.batch_alter_table('room_night_approval', schema=None) as batch_op:
        batch_op.create_foreign_key('room_night_approval_room_night_request_fkey', 'room_night_request', ['room_night'], ['id'])

    with op.batch_alter_table('hotel_location', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('badge', schema=None) as batch_op:
        batch_op.drop_column('emergency_contact_phone')
        batch_op.drop_column('emergency_contact_name')
        batch_op.drop_column('public_name')

    # ### end Alembic commands ###
