"""Expanding deletion cascades when deleting an event

Revision ID: 5358d76ff848
Revises: 6fe96ce9e06a
Create Date: 2022-11-20 15:46:16.827279

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5358d76ff848'
down_revision = '6fe96ce9e06a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('badge_to_department', schema=None) as batch_op:
        batch_op.drop_constraint('badge_to_department_badge_fkey', type_='foreignkey')
        batch_op.drop_constraint('badge_to_department_department_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'badge', ['badge'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'department', ['department'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('department_grant', schema=None) as batch_op:
        batch_op.drop_constraint('department_grant_event_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'event', ['event'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('department_permission', schema=None) as batch_op:
        batch_op.drop_constraint('department_permission_event_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'event', ['event'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('department_role', schema=None) as batch_op:
        batch_op.drop_constraint('department_role_event_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'event', ['event'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('hotel_location', schema=None) as batch_op:
        batch_op.drop_constraint('hotel_location_event_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'event', ['event'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('ribbon_to_badge', schema=None) as batch_op:
        batch_op.drop_constraint('ribbon_to_badge_badge_fkey', type_='foreignkey')
        batch_op.drop_constraint('ribbon_to_badge_ribbon_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'ribbon_type', ['ribbon'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'badge', ['badge'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ribbon_to_badge', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('ribbon_to_badge_ribbon_fkey', 'ribbon_type', ['ribbon'], ['id'])
        batch_op.create_foreign_key('ribbon_to_badge_badge_fkey', 'badge', ['badge'], ['id'])

    with op.batch_alter_table('hotel_location', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('hotel_location_event_fkey', 'event', ['event'], ['id'])

    with op.batch_alter_table('department_role', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('department_role_event_fkey', 'event', ['event'], ['id'])

    with op.batch_alter_table('department_permission', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('department_permission_event_fkey', 'event', ['event'], ['id'])

    with op.batch_alter_table('department_grant', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('department_grant_event_fkey', 'event', ['event'], ['id'])

    with op.batch_alter_table('badge_to_department', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('badge_to_department_department_fkey', 'department', ['department'], ['id'])
        batch_op.create_foreign_key('badge_to_department_badge_fkey', 'badge', ['badge'], ['id'])

    # ### end Alembic commands ###
