"""Adding created and modified times to everything

Revision ID: 53a92676ee86
Revises: 7e310668394d
Create Date: 2022-11-21 22:53:18.370871

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53a92676ee86'
down_revision = '7e310668394d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('api_key', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created', sa.DateTime(
        ), server_default=sa.text('now()'), nullable=True))
        batch_op.add_column(sa.Column('modified', sa.DateTime(
        ), server_default=sa.text('now()'), nullable=True))

    with op.batch_alter_table('background_job', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created', sa.DateTime(
        ), server_default=sa.text('now()'), nullable=True))
        batch_op.add_column(sa.Column('modified', sa.DateTime(
        ), server_default=sa.text('now()'), nullable=True))

    with op.batch_alter_table('badge', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created', sa.DateTime(
        ), server_default=sa.text('now()'), nullable=True))
        batch_op.add_column(sa.Column('modified', sa.DateTime(
        ), server_default=sa.text('now()'), nullable=True))

    with op.batch_alter_table('badge_to_department', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created', sa.DateTime(
        ), server_default=sa.text('now()'), nullable=True))
        batch_op.add_column(sa.Column('modified', sa.DateTime(
        ), server_default=sa.text('now()'), nullable=True))

    with op.batch_alter_table('badge_type', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created', sa.DateTime(
        ), server_default=sa.text('now()'), nullable=True))
        batch_op.add_column(sa.Column('modified', sa.DateTime(
        ), server_default=sa.text('now()'), nullable=True))

    with op.batch_alter_table('department', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created', sa.DateTime(
        ), server_default=sa.text('now()'), nullable=True))
        batch_op.add_column(sa.Column('modified', sa.DateTime(
        ), server_default=sa.text('now()'), nullable=True))

    with op.batch_alter_table('department_grant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created', sa.DateTime(
        ), server_default=sa.text('now()'), nullable=True))
        batch_op.add_column(sa.Column('modified', sa.DateTime(
        ), server_default=sa.text('now()'), nullable=True))

    with op.batch_alter_table('department_permission', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created', sa.DateTime(
        ), server_default=sa.text('now()'), nullable=True))
        batch_op.add_column(sa.Column('modified', sa.DateTime(
        ), server_default=sa.text('now()'), nullable=True))

    with op.batch_alter_table('department_role', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created', sa.DateTime(
        ), server_default=sa.text('now()'), nullable=True))
        batch_op.add_column(sa.Column('modified', sa.DateTime(
        ), server_default=sa.text('now()'), nullable=True))

    with op.batch_alter_table('email', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created', sa.DateTime(
        ), server_default=sa.text('now()'), nullable=True))
        batch_op.add_column(sa.Column('modified', sa.DateTime(
        ), server_default=sa.text('now()'), nullable=True))

    with op.batch_alter_table('email_receipt', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created', sa.DateTime(
        ), server_default=sa.text('now()'), nullable=True))
        batch_op.add_column(sa.Column('modified', sa.DateTime(
        ), server_default=sa.text('now()'), nullable=True))

    with op.batch_alter_table('email_source', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created', sa.DateTime(
        ), server_default=sa.text('now()'), nullable=True))
        batch_op.add_column(sa.Column('modified', sa.DateTime(
        ), server_default=sa.text('now()'), nullable=True))

    with op.batch_alter_table('email_trigger', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created', sa.DateTime(
        ), server_default=sa.text('now()'), nullable=True))
        batch_op.add_column(sa.Column('modified', sa.DateTime(
        ), server_default=sa.text('now()'), nullable=True))

    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created', sa.DateTime(
        ), server_default=sa.text('now()'), nullable=True))
        batch_op.add_column(sa.Column('modified', sa.DateTime(
        ), server_default=sa.text('now()'), nullable=True))

    with op.batch_alter_table('grant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created', sa.DateTime(
        ), server_default=sa.text('now()'), nullable=True))
        batch_op.add_column(sa.Column('modified', sa.DateTime(
        ), server_default=sa.text('now()'), nullable=True))

    with op.batch_alter_table('hotel_anti_roommate_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created', sa.DateTime(
        ), server_default=sa.text('now()'), nullable=True))
        batch_op.add_column(sa.Column('modified', sa.DateTime(
        ), server_default=sa.text('now()'), nullable=True))

    with op.batch_alter_table('hotel_location', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created', sa.DateTime(
        ), server_default=sa.text('now()'), nullable=True))
        batch_op.add_column(sa.Column('modified', sa.DateTime(
        ), server_default=sa.text('now()'), nullable=True))

    with op.batch_alter_table('hotel_room', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created', sa.DateTime(
        ), server_default=sa.text('now()'), nullable=True))
        batch_op.add_column(sa.Column('modified', sa.DateTime(
        ), server_default=sa.text('now()'), nullable=True))

    with op.batch_alter_table('hotel_room_block', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created', sa.DateTime(
        ), server_default=sa.text('now()'), nullable=True))
        batch_op.add_column(sa.Column('modified', sa.DateTime(
        ), server_default=sa.text('now()'), nullable=True))

    with op.batch_alter_table('hotel_room_night', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created', sa.DateTime(
        ), server_default=sa.text('now()'), nullable=True))
        batch_op.add_column(sa.Column('modified', sa.DateTime(
        ), server_default=sa.text('now()'), nullable=True))

    with op.batch_alter_table('hotel_room_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created', sa.DateTime(
        ), server_default=sa.text('now()'), nullable=True))
        batch_op.add_column(sa.Column('modified', sa.DateTime(
        ), server_default=sa.text('now()'), nullable=True))

    with op.batch_alter_table('hotel_roommate_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created', sa.DateTime(
        ), server_default=sa.text('now()'), nullable=True))
        batch_op.add_column(sa.Column('modified', sa.DateTime(
        ), server_default=sa.text('now()'), nullable=True))

    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created', sa.DateTime(
        ), server_default=sa.text('now()'), nullable=True))
        batch_op.add_column(sa.Column('modified', sa.DateTime(
        ), server_default=sa.text('now()'), nullable=True))

    with op.batch_alter_table('job_role_association', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created', sa.DateTime(
        ), server_default=sa.text('now()'), nullable=True))
        batch_op.add_column(sa.Column('modified', sa.DateTime(
        ), server_default=sa.text('now()'), nullable=True))

    with op.batch_alter_table('job_schedule_association', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created', sa.DateTime(
        ), server_default=sa.text('now()'), nullable=True))
        batch_op.add_column(sa.Column('modified', sa.DateTime(
        ), server_default=sa.text('now()'), nullable=True))

    with op.batch_alter_table('job_schedule_event_association', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created', sa.DateTime(
        ), server_default=sa.text('now()'), nullable=True))
        batch_op.add_column(sa.Column('modified', sa.DateTime(
        ), server_default=sa.text('now()'), nullable=True))

    with op.batch_alter_table('permission', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created', sa.DateTime(
        ), server_default=sa.text('now()'), nullable=True))
        batch_op.add_column(sa.Column('modified', sa.DateTime(
        ), server_default=sa.text('now()'), nullable=True))

    with op.batch_alter_table('ribbon_to_badge', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created', sa.DateTime(
        ), server_default=sa.text('now()'), nullable=True))
        batch_op.add_column(sa.Column('modified', sa.DateTime(
        ), server_default=sa.text('now()'), nullable=True))

    with op.batch_alter_table('ribbon_type', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created', sa.DateTime(
        ), server_default=sa.text('now()'), nullable=True))
        batch_op.add_column(sa.Column('modified', sa.DateTime(
        ), server_default=sa.text('now()'), nullable=True))

    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created', sa.DateTime(
        ), server_default=sa.text('now()'), nullable=True))
        batch_op.add_column(sa.Column('modified', sa.DateTime(
        ), server_default=sa.text('now()'), nullable=True))

    with op.batch_alter_table('room_night_approval', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created', sa.DateTime(
        ), server_default=sa.text('now()'), nullable=True))
        batch_op.add_column(sa.Column('modified', sa.DateTime(
        ), server_default=sa.text('now()'), nullable=True))

    with op.batch_alter_table('room_night_assignment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created', sa.DateTime(
        ), server_default=sa.text('now()'), nullable=True))
        batch_op.add_column(sa.Column('modified', sa.DateTime(
        ), server_default=sa.text('now()'), nullable=True))

    with op.batch_alter_table('room_night_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created', sa.DateTime(
        ), server_default=sa.text('now()'), nullable=True))
        batch_op.add_column(sa.Column('modified', sa.DateTime(
        ), server_default=sa.text('now()'), nullable=True))

    with op.batch_alter_table('schedule', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created', sa.DateTime(
        ), server_default=sa.text('now()'), nullable=True))
        batch_op.add_column(sa.Column('modified', sa.DateTime(
        ), server_default=sa.text('now()'), nullable=True))

    with op.batch_alter_table('schedule_event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created', sa.DateTime(
        ), server_default=sa.text('now()'), nullable=True))
        batch_op.add_column(sa.Column('modified', sa.DateTime(
        ), server_default=sa.text('now()'), nullable=True))

    with op.batch_alter_table('session', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created', sa.DateTime(
        ), server_default=sa.text('now()'), nullable=True))
        batch_op.add_column(sa.Column('modified', sa.DateTime(
        ), server_default=sa.text('now()'), nullable=True))

    with op.batch_alter_table('shift', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created', sa.DateTime(
        ), server_default=sa.text('now()'), nullable=True))
        batch_op.add_column(sa.Column('modified', sa.DateTime(
        ), server_default=sa.text('now()'), nullable=True))

    with op.batch_alter_table('shift_assignment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created', sa.DateTime(
        ), server_default=sa.text('now()'), nullable=True))
        batch_op.add_column(sa.Column('modified', sa.DateTime(
        ), server_default=sa.text('now()'), nullable=True))

    with op.batch_alter_table('shift_signup', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created', sa.DateTime(
        ), server_default=sa.text('now()'), nullable=True))
        batch_op.add_column(sa.Column('modified', sa.DateTime(
        ), server_default=sa.text('now()'), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created', sa.DateTime(
        ), server_default=sa.text('now()'), nullable=True))
        batch_op.add_column(sa.Column('modified', sa.DateTime(
        ), server_default=sa.text('now()'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('modified')
        batch_op.drop_column('created')

    with op.batch_alter_table('shift_signup', schema=None) as batch_op:
        batch_op.drop_column('modified')
        batch_op.drop_column('created')

    with op.batch_alter_table('shift_assignment', schema=None) as batch_op:
        batch_op.drop_column('modified')
        batch_op.drop_column('created')

    with op.batch_alter_table('shift', schema=None) as batch_op:
        batch_op.drop_column('modified')
        batch_op.drop_column('created')

    with op.batch_alter_table('session', schema=None) as batch_op:
        batch_op.drop_column('modified')
        batch_op.drop_column('created')

    with op.batch_alter_table('schedule_event', schema=None) as batch_op:
        batch_op.drop_column('modified')
        batch_op.drop_column('created')

    with op.batch_alter_table('schedule', schema=None) as batch_op:
        batch_op.drop_column('modified')
        batch_op.drop_column('created')

    with op.batch_alter_table('room_night_request', schema=None) as batch_op:
        batch_op.drop_column('modified')
        batch_op.drop_column('created')

    with op.batch_alter_table('room_night_assignment', schema=None) as batch_op:
        batch_op.drop_column('modified')
        batch_op.drop_column('created')

    with op.batch_alter_table('room_night_approval', schema=None) as batch_op:
        batch_op.drop_column('modified')
        batch_op.drop_column('created')

    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.drop_column('modified')
        batch_op.drop_column('created')

    with op.batch_alter_table('ribbon_type', schema=None) as batch_op:
        batch_op.drop_column('modified')
        batch_op.drop_column('created')

    with op.batch_alter_table('ribbon_to_badge', schema=None) as batch_op:
        batch_op.drop_column('modified')
        batch_op.drop_column('created')

    with op.batch_alter_table('permission', schema=None) as batch_op:
        batch_op.drop_column('modified')
        batch_op.drop_column('created')

    with op.batch_alter_table('job_schedule_event_association', schema=None) as batch_op:
        batch_op.drop_column('modified')
        batch_op.drop_column('created')

    with op.batch_alter_table('job_schedule_association', schema=None) as batch_op:
        batch_op.drop_column('modified')
        batch_op.drop_column('created')

    with op.batch_alter_table('job_role_association', schema=None) as batch_op:
        batch_op.drop_column('modified')
        batch_op.drop_column('created')

    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.drop_column('modified')
        batch_op.drop_column('created')

    with op.batch_alter_table('hotel_roommate_request', schema=None) as batch_op:
        batch_op.drop_column('modified')
        batch_op.drop_column('created')

    with op.batch_alter_table('hotel_room_request', schema=None) as batch_op:
        batch_op.drop_column('modified')
        batch_op.drop_column('created')

    with op.batch_alter_table('hotel_room_night', schema=None) as batch_op:
        batch_op.drop_column('modified')
        batch_op.drop_column('created')

    with op.batch_alter_table('hotel_room_block', schema=None) as batch_op:
        batch_op.drop_column('modified')
        batch_op.drop_column('created')

    with op.batch_alter_table('hotel_room', schema=None) as batch_op:
        batch_op.drop_column('modified')
        batch_op.drop_column('created')

    with op.batch_alter_table('hotel_location', schema=None) as batch_op:
        batch_op.drop_column('modified')
        batch_op.drop_column('created')

    with op.batch_alter_table('hotel_anti_roommate_request', schema=None) as batch_op:
        batch_op.drop_column('modified')
        batch_op.drop_column('created')

    with op.batch_alter_table('grant', schema=None) as batch_op:
        batch_op.drop_column('modified')
        batch_op.drop_column('created')

    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_column('modified')
        batch_op.drop_column('created')

    with op.batch_alter_table('email_trigger', schema=None) as batch_op:
        batch_op.drop_column('modified')
        batch_op.drop_column('created')

    with op.batch_alter_table('email_source', schema=None) as batch_op:
        batch_op.drop_column('modified')
        batch_op.drop_column('created')

    with op.batch_alter_table('email_receipt', schema=None) as batch_op:
        batch_op.drop_column('modified')
        batch_op.drop_column('created')

    with op.batch_alter_table('email', schema=None) as batch_op:
        batch_op.drop_column('modified')
        batch_op.drop_column('created')

    with op.batch_alter_table('department_role', schema=None) as batch_op:
        batch_op.drop_column('modified')
        batch_op.drop_column('created')

    with op.batch_alter_table('department_permission', schema=None) as batch_op:
        batch_op.drop_column('modified')
        batch_op.drop_column('created')

    with op.batch_alter_table('department_grant', schema=None) as batch_op:
        batch_op.drop_column('modified')
        batch_op.drop_column('created')

    with op.batch_alter_table('department', schema=None) as batch_op:
        batch_op.drop_column('modified')
        batch_op.drop_column('created')

    with op.batch_alter_table('badge_type', schema=None) as batch_op:
        batch_op.drop_column('modified')
        batch_op.drop_column('created')

    with op.batch_alter_table('badge_to_department', schema=None) as batch_op:
        batch_op.drop_column('modified')
        batch_op.drop_column('created')

    with op.batch_alter_table('badge', schema=None) as batch_op:
        batch_op.drop_column('modified')
        batch_op.drop_column('created')

    with op.batch_alter_table('background_job', schema=None) as batch_op:
        batch_op.drop_column('modified')
        batch_op.drop_column('created')

    with op.batch_alter_table('api_key', schema=None) as batch_op:
        batch_op.drop_column('modified')
        batch_op.drop_column('created')

    # ### end Alembic commands ###
