"""added backgroundjobs

Revision ID: 542fdb87670c
Revises: 7a98a0c9fb44
Create Date: 2021-05-09 17:48:39.548660

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '542fdb87670c'
down_revision = '7a98a0c9fb44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('background_job',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session', sa.Integer(), nullable=True),
    sa.Column('uuid', sa.String(), nullable=False),
    sa.Column('progress', sa.JSON(), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('created', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('modified', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['session'], ['session.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('background_job')
    # ### end Alembic commands ###
