"""Adding readonly column to event and allowing users to choose a default event

Revision ID: 6fe96ce9e06a
Revises: f22ada79538c
Create Date: 2022-11-19 20:02:36.934950

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fe96ce9e06a'
down_revision = 'f22ada79538c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email', schema=None) as batch_op:
        batch_op.drop_constraint('email_name_key', type_='unique')

    with op.batch_alter_table('email_source', schema=None) as batch_op:
        batch_op.drop_constraint('email_source_name_key', type_='unique')

    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('readonly', sa.Boolean(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('default_event', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'event', ['default_event'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('default_event')

    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_column('readonly')

    with op.batch_alter_table('email_source', schema=None) as batch_op:
        batch_op.create_unique_constraint('email_source_name_key', ['name'])

    with op.batch_alter_table('email', schema=None) as batch_op:
        batch_op.create_unique_constraint('email_name_key', ['name'])

    # ### end Alembic commands ###
