"""Adding reapproved field to hotel_request

Revision ID: 844962e6352c
Revises: 03fa60ed8de2
Create Date: 2021-11-20 01:34:27.064771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '844962e6352c'
down_revision = '03fa60ed8de2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hotel_room_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('approved', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hotel_room_request', schema=None) as batch_op:
        batch_op.drop_column('approved')

    # ### end Alembic commands ###
