"""Renamed event_id to event

Revision ID: a1869a1eb145
Revises: 528cd10edcce
Create Date: 2019-11-21 20:01:32.404974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1869a1eb145'
down_revision = '528cd10edcce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('badge', schema=None) as batch_op:
        batch_op.alter_column('event_id', nullable=False, new_column_name='event')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('badge', schema=None) as batch_op:
        batch_op.alter_column('event', nullable=False, new_column_name='event_id')


    # ### end Alembic commands ###
