"""New Frontend

Revision ID: a19f71e34e64
Revises: 542fdb87670c
Create Date: 2021-10-25 13:31:01.056139

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a19f71e34e64'
down_revision = '542fdb87670c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department_role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('event', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['event'], ['event.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('department_grant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.Integer(), nullable=True),
    sa.Column('event', sa.Integer(), nullable=True),
    sa.Column('role', sa.Integer(), nullable=True),
    sa.Column('department', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['department'], ['department.id'], ),
    sa.ForeignKeyConstraint(['event'], ['event.id'], ),
    sa.ForeignKeyConstraint(['role'], ['department_role.id'], ),
    sa.ForeignKeyConstraint(['user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('department_permission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('event', sa.Integer(), nullable=True),
    sa.Column('role', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['event'], ['event.id'], ),
    sa.ForeignKeyConstraint(['role'], ['department_role.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('background_job', schema=None) as batch_op:
        batch_op.add_column(sa.Column('context', sa.JSON(), nullable=True))
        batch_op.alter_column('uuid',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('badge', schema=None) as batch_op:
        batch_op.alter_column('event',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('legal_name',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)

    with op.batch_alter_table('badge_to_department', schema=None) as batch_op:
        batch_op.alter_column('badge',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('department',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('badge_type', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)

    with op.batch_alter_table('department', schema=None) as batch_op:
        batch_op.alter_column('event',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('email', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)
        batch_op.alter_column('event',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('subject',
               existing_type=sa.VARCHAR(length=4096),
               nullable=True)
        batch_op.alter_column('body',
               existing_type=sa.VARCHAR(length=4096),
               nullable=True)
        batch_op.alter_column('active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('send_once',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    with op.batch_alter_table('email_receipt', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trigger', sa.Integer(), nullable=True))
        batch_op.alter_column('to_address',
               existing_type=sa.VARCHAR(length=1024),
               nullable=True)
        batch_op.alter_column('from_address',
               existing_type=sa.VARCHAR(length=1024),
               nullable=True)
        batch_op.alter_column('subject',
               existing_type=sa.VARCHAR(length=4096),
               nullable=True)
        batch_op.alter_column('body',
               existing_type=sa.VARCHAR(length=4096),
               nullable=True)
        batch_op.alter_column('timestamp',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.create_foreign_key(None, 'email_trigger', ['trigger'], ['id'])

    with op.batch_alter_table('email_source', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
        batch_op.alter_column('event',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('address',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
        batch_op.alter_column('region',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
        batch_op.alter_column('ses_access_key',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
        batch_op.alter_column('ses_secret_key',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)

    with op.batch_alter_table('email_trigger', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(), nullable=True))
        batch_op.alter_column('trigger',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
        batch_op.drop_constraint('email_trigger_badge_fkey', type_='foreignkey')
        batch_op.drop_column('badge')

    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)

    with op.batch_alter_table('grant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event', sa.Integer(), nullable=True))
        batch_op.alter_column('user',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('role',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.create_foreign_key(None, 'event', ['event'], ['id'])
        batch_op.create_foreign_key(None, 'role', ['role'], ['id'])
        batch_op.drop_column('department')

    with op.batch_alter_table('hotel_anti_roommate_request', schema=None) as batch_op:
        batch_op.alter_column('requester',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('requested',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('hotel_location', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=32),
               nullable=True)
        batch_op.alter_column('address',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
        batch_op.alter_column('event',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('hotel_room', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event', sa.Integer(), nullable=True))
        batch_op.alter_column('hotel_block',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('hotel_location',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_foreign_key(None, 'event', ['event'], ['id'])

    with op.batch_alter_table('hotel_room_night', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.Date(), nullable=True))
        batch_op.alter_column('event',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=16),
               nullable=True)
        batch_op.alter_column('restricted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('hidden',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))

    with op.batch_alter_table('hotel_room_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event', sa.Integer(), nullable=True))
        batch_op.alter_column('badge',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_foreign_key(None, 'event', ['event'], ['id'])

    with op.batch_alter_table('hotel_roommate_request', schema=None) as batch_op:
        batch_op.alter_column('requester',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('requested',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('job_role_association', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event', sa.Integer(), nullable=True))
        batch_op.drop_constraint('job_role_association_role_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'event', ['event'], ['id'])
        batch_op.create_foreign_key(None, 'department_role', ['role'], ['id'])

    with op.batch_alter_table('job_schedule_association', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'event', ['event'], ['id'])

    with op.batch_alter_table('job_schedule_event_association', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'event', ['event'], ['id'])

    with op.batch_alter_table('permission', schema=None) as batch_op:
        batch_op.drop_constraint('permission_operation_key', type_='unique')

    with op.batch_alter_table('ribbon_type', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)

    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.drop_column('event')

    with op.batch_alter_table('room_night_approval', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event', sa.Integer(), nullable=True))
        batch_op.alter_column('badge',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('room_night',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('department',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('approved',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.create_foreign_key(None, 'event', ['event'], ['id'])

    with op.batch_alter_table('room_night_assignment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event', sa.Integer(), nullable=True))
        batch_op.alter_column('room_night',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_foreign_key(None, 'event', ['event'], ['id'])

    with op.batch_alter_table('room_night_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event', sa.Integer(), nullable=True))
        batch_op.alter_column('badge',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('room_night',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_foreign_key(None, 'event', ['event'], ['id'])

    with op.batch_alter_table('schedule_event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'event', ['event'], ['id'])

    with op.batch_alter_table('session', schema=None) as batch_op:
        batch_op.add_column(sa.Column('permissions', sa.JSON(), nullable=True))

    with op.batch_alter_table('shift', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'event', ['event'], ['id'])

    with op.batch_alter_table('shift_assignment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'event', ['event'], ['id'])

    with op.batch_alter_table('shift_signup', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'event', ['event'], ['id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)

    with op.batch_alter_table('shift_signup', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('event')

    with op.batch_alter_table('shift_assignment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('event')

    with op.batch_alter_table('shift', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('event')

    with op.batch_alter_table('session', schema=None) as batch_op:
        batch_op.drop_column('permissions')

    with op.batch_alter_table('schedule_event', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('event')

    with op.batch_alter_table('room_night_request', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('room_night',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('badge',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('event')

    with op.batch_alter_table('room_night_assignment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('room_night',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('event')

    with op.batch_alter_table('room_night_approval', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('approved',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('department',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('room_night',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('badge',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('event')

    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event', sa.INTEGER(), autoincrement=False, nullable=True))

    with op.batch_alter_table('ribbon_type', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)

    with op.batch_alter_table('permission', schema=None) as batch_op:
        batch_op.create_unique_constraint('permission_operation_key', ['operation'])

    with op.batch_alter_table('job_schedule_event_association', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('event')

    with op.batch_alter_table('job_schedule_association', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('event')

    with op.batch_alter_table('job_role_association', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('job_role_association_role_fkey', 'role', ['role'], ['id'])
        batch_op.drop_column('event')

    with op.batch_alter_table('hotel_roommate_request', schema=None) as batch_op:
        batch_op.alter_column('requested',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('requester',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('hotel_room_request', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('badge',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('event')

    with op.batch_alter_table('hotel_room_night', schema=None) as batch_op:
        batch_op.alter_column('hidden',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
        batch_op.alter_column('restricted',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=16),
               nullable=False)
        batch_op.alter_column('event',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('date')

    with op.batch_alter_table('hotel_room', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('hotel_location',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('hotel_block',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('event')

    with op.batch_alter_table('hotel_location', schema=None) as batch_op:
        batch_op.alter_column('event',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('address',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=32),
               nullable=False)

    with op.batch_alter_table('hotel_anti_roommate_request', schema=None) as batch_op:
        batch_op.alter_column('requested',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('requester',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('grant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('department', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('role',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('user',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('event')

    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)

    with op.batch_alter_table('email_trigger', schema=None) as batch_op:
        batch_op.add_column(sa.Column('badge', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('email_trigger_badge_fkey', 'badge', ['badge'], ['id'])
        batch_op.alter_column('trigger',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
        batch_op.drop_column('timestamp')

    with op.batch_alter_table('email_source', schema=None) as batch_op:
        batch_op.alter_column('ses_secret_key',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
        batch_op.alter_column('ses_access_key',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
        batch_op.alter_column('region',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
        batch_op.alter_column('address',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
        batch_op.alter_column('event',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)

    with op.batch_alter_table('email_receipt', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('timestamp',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.alter_column('body',
               existing_type=sa.VARCHAR(length=4096),
               nullable=False)
        batch_op.alter_column('subject',
               existing_type=sa.VARCHAR(length=4096),
               nullable=False)
        batch_op.alter_column('from_address',
               existing_type=sa.VARCHAR(length=1024),
               nullable=False)
        batch_op.alter_column('to_address',
               existing_type=sa.VARCHAR(length=1024),
               nullable=False)
        batch_op.drop_column('trigger')

    with op.batch_alter_table('email', schema=None) as batch_op:
        batch_op.alter_column('send_once',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('body',
               existing_type=sa.VARCHAR(length=4096),
               nullable=False)
        batch_op.alter_column('subject',
               existing_type=sa.VARCHAR(length=4096),
               nullable=False)
        batch_op.alter_column('event',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)

    with op.batch_alter_table('department', schema=None) as batch_op:
        batch_op.alter_column('event',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('badge_type', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)

    with op.batch_alter_table('badge_to_department', schema=None) as batch_op:
        batch_op.alter_column('department',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('badge',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('badge', schema=None) as batch_op:
        batch_op.alter_column('legal_name',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)
        batch_op.alter_column('event',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('background_job', schema=None) as batch_op:
        batch_op.alter_column('uuid',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_column('context')

    op.drop_table('department_permission')
    op.drop_table('department_grant')
    op.drop_table('department_role')
    # ### end Alembic commands ###
