"""Added shift start and end times to hotelroomnight

Revision ID: afc23d43704e
Revises: 44ea59b15fb5
Create Date: 2025-06-25 21:22:11.475460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afc23d43704e'
down_revision = '44ea59b15fb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hotel_room_night', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shift_starttime', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('shift_endtime', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hotel_room_night', schema=None) as batch_op:
        batch_op.drop_column('shift_endtime')
        batch_op.drop_column('shift_starttime')

    # ### end Alembic commands ###
