"""Remove description, add notes and messages

Revision ID: 45c5e6536c03
Revises: 7340c2537750
Create Date: 2019-11-21 00:21:08.555405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45c5e6536c03'
down_revision = '7340c2537750'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hotel_room', schema=None) as batch_op:
        batch_op.add_column(sa.Column('messages', sa.String(length=512), nullable=True))
        batch_op.add_column(sa.Column('notes', sa.String(length=512), nullable=True))
        batch_op.drop_column('description')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hotel_room', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.VARCHAR(length=256), nullable=True))
        batch_op.drop_column('notes')
        batch_op.drop_column('messages')

    # ### end Alembic commands ###
