"""Adding hotel_room to badge_to_room_night, adding event to hotel_location, and removing disable_autofill from hotel_room

Revision ID: 597fbaa68dad
Revises: b9644d65529a
Create Date: 2019-11-19 23:56:47.351781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '597fbaa68dad'
down_revision = 'b9644d65529a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hotel_location', schema=None) as batch_op:
        batch_op.create_foreign_key("event_fk", 'event', ['event'], ['id'])

    with op.batch_alter_table('hotel_room', schema=None) as batch_op:
        batch_op.drop_column('disable_autofill')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hotel_room', schema=None) as batch_op:
        batch_op.add_column(sa.Column('disable_autofill', sa.BOOLEAN(), nullable=False))

    with op.batch_alter_table('hotel_location', schema=None) as batch_op:
        batch_op.drop_constraint("event_fk", type_='foreignkey')

    # ### end Alembic commands ###
