"""Added event field to HotelRoom

Revision ID: ad4ebdb80373
Revises: 45c5e6536c03
Create Date: 2019-11-21 00:56:17.245072

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad4ebdb80373'
down_revision = '45c5e6536c03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hotel_room', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('hotel_room_event_fk', 'event', ['event'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hotel_room', schema=None) as batch_op:
        batch_op.drop_constraint('hotel_room_event_fk', type_='foreignkey')
        batch_op.drop_column('event')
    # ### end Alembic commands ###
