"""Add hidden room nights for edge-edge nights

Revision ID: ba06f3351d89
Revises: 45c5e6536c03
Create Date: 2019-11-21 00:53:33.627380

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba06f3351d89'
down_revision = '45c5e6536c03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hotel_room_night', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hidden', sa.Boolean(), nullable=False, server_default='false'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hotel_room_night', schema=None) as batch_op:
        batch_op.drop_column('hidden')

    # ### end Alembic commands ###
