"""Allow null badge in badge_to_room_night for possible placeholders

Revision ID: 7340c2537750
Revises: f60794f1f9fd
Create Date: 2019-11-21 00:19:44.346650

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7340c2537750'
down_revision = 'f60794f1f9fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('badge_to_room_night', schema=None) as batch_op:
        batch_op.alter_column('badge',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('badge_to_room_night', schema=None) as batch_op:
        batch_op.alter_column('badge',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
